[package]
name = "savegame_analysis"
version = "0.1.0"
authors = ["kangalioo"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
rayon = "1.3"
btoi = "0.4"
lexical = "5"

[dependencies.pyo3]
version = "0.9.2"
features = ["extension-module"]

[profile.release]
debug = true
lto = true
