name: Compile savegame_analysis

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: nightly
    
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    
    - uses: actions/checkout@v2
    
    - name: Build
      run: cargo build --release
      working-directory: ./savegame_analysis
    
    - uses: actions/upload-artifact@v2
      with:
        name: savegame_analysis.pyd
        path: savegame_analysis/target/release/savegame_analysis.dll
