name: Compile, bundle and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  _: # man this workflow already has a name. I don't need two names for one thing
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        include:
        - os: windows-latest
          LIBRARY_FILENAME: savegame_analysis.dll
          PYMODULE_FILENAME: savegame_analysis.pyd
        - os: ubuntu-latest
          LIBRARY_FILENAME: libsavegame_analysis.so
          PYMODULE_FILENAME: savegame_analysis.so
    runs-on: ${{ matrix.os }}
  
    steps:
    
    # Setup
    
    - uses: actions/checkout@v2
    
    - name: Setup Rust
      uses: hecrj/setup-rust-action@v1
      with:
        rust-version: nightly
    
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
    
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    
    - name: Unit-test savegame_analysis
      run: cargo test
      working-directory: ./savegame_analysis
    
    - name: Build savegame_analysis
      run: cargo build --release --features extension-module
      working-directory: ./savegame_analysis
    
    - name: Rename Python module file extension and move
      run: mv savegame_analysis/target/release/${{matrix.LIBRARY_FILENAME}} ${{matrix.PYMODULE_FILENAME}}
    
    - name: Strip library
      if: startsWith(matrix.os, 'ubuntu')
      run: strip ${{matrix.PYMODULE_FILENAME}}
    
    # Bundled exe
    
    - name: Copy savegame_analysis module to src
      run: cp ${{matrix.PYMODULE_FILENAME}} src/${{matrix.PYMODULE_FILENAME}}
    
    - name: Bundle exe
      if: startsWith(matrix.os, 'windows')
      run: .\bundle.bat
    
    # Upload
    
    - name: Upload bundled exe
      uses: actions/upload-artifact@v2
      if: startsWith(matrix.os, 'windows')
      with:
        name: Bundled exe
        path: EtternaGraph.exe
    
    - name: Upload compiled module
      uses: actions/upload-artifact@v2
      with:
        name: Compiled savegame_analysis modules
        path: ${{matrix.PYMODULE_FILENAME}}
