name: Compile savegame_analysis

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        include:
        - os: windows-latest
          LIBRARY_EXTENSION: dll
          PYMODULE_EXTENSION: pyd
        - os: ubuntu-latest
          LIBRARY_EXTENSION: so
          PYMODULE_EXTENSION: so

    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: nightly
    
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    
    - uses: actions/checkout@v2
    
    - name: Build
      run: cargo build --release
      working-directory: ./savegame_analysis
    
    - name: Rename Python module file extension and move
      run: mv savegame_analysis/target/release/savegame_analysis.${{matrix.LIBRARY_EXTENSION}} savegame_analysis.${{matrix.PYMODULE_EXTENSION}}
    
    - uses: actions/upload-artifact@v2
      with:
        path: savegame_analysis.${{matrix.PYMODULE_EXTENSION}}
