name: Compile savegame_analysis

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        include:
        - os: windows-latest
          LIBRARY_FILENAME: savegame_analysis.dll
          PYMODULE_FILENAME: savegame_analysis.pyd
        - os: ubuntu-latest
          LIBRARY_FILENAME: libsavegame_analysis.so
          PYMODULE_FILENAME: savegame_analysis.so

    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: nightly
    
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    
    - uses: actions/checkout@v2
    
    - name: Build
      run: cargo build --release
      working-directory: ./savegame_analysis
    
    - name: Rename Python module file extension and move
      run: mv savegame_analysis/target/release/${{matrix.LIBRARY_FILENAME}} ${{matrix.PYMODULE_FILENAME}}
    
    - name: Strip library
      if: startsWith(matrix.os, 'ubuntu')
      run: strip ${{matrix.PYMODULE_FILENAME}}
    
    - uses: actions/upload-artifact@v2
      with:
        name: Compiled savegame_analysis modules
        path: ${{matrix.PYMODULE_FILENAME}}
